name: CI

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  # environment vars
  DIST_ARTIFACT: dist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Build
        run: npm run build
        shell: bash

  lint:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: ESLint
        run: npm run lint:eslint
        shell: bash

      - name: Prettier
        run: npm run lint:prettier
        shell: bash

      - name: SCSS Lint
        run: npm run lint:scss
        shell: bash

  test:
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Unit Tests
        run: npm run test
        shell: bash

  e2e-test:
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: E2E Tests
        run: echo Run e2e tests
        shell: bash

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
      - test
      - e2e-test
    steps:
      - name: Deploy to given platform
        run: echo Deploy to given platform
        shell: bash
