name: CI
description: 'CI Build Pipeline'

on:
  workflow_dispatch:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

env:
  # environment vars
  DIST_ARTIFACT: dist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: setup
      - uses: ./.github/actions/setup

      - name: build
        run: npm run build

  lint:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - id: setup
      - uses: ./.github/actions/setup

      - name: lint:eslint
      - run: npm run lint:eslint

      - name: lint:prettier
      - run: npm run lint:prettier

      - name: lint:scss
      - run: npm run lint:scss

  test:
    runs-on: ubuntu-latest
    needs:
      - build
      - lint

    steps:
      - id: setup
      - uses: ./.github/actions/setup

      - name: unit tests
      - run: npm run test

  e2e-test:
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
    steps:
      - id: setup
      - uses: ./.github/actions/setup

      - name: e2e tests
      - run: echo Run e2e tests

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
      - test
      - e2e-test

    steps:
      - name: Deploy to given platform
        run: echo Deploy to given platform
